[colors.primary]
background = '#17130b'
foreground = '#ebe1d4'

[colors.selection]
text = '#ebe1d4'
background = '#4a3c00'

[colors.cursor]
text = '#17130b'
cursor = '#ffc107'

[colors.normal]
black   = '#17130b'
red     = '#ff1b02'
green   = '#2aff07'
yellow  = '#ffd500'
blue    = '#f2b500'
magenta = '#765800'
cyan    = '#ffc107'
white   = '#fff7e1'

[colors.bright]
black   = '#a59f8d'
red     = '#ff5545'
green   = '#6aff51'
yellow  = '#ffe251'
blue    = '#ffca2c'
magenta = '#ffd351'
cyan    = '#ffe38f'
white   = '#fffbf2'
