# Gruvbox Light — applicato automaticamente in modalità chiara

# Base
foreground            #3c3836
background            #fbf1c7
selection_foreground  #fbf1c7
selection_background  #3c3836
cursor                #3c3836
cursor_text_color     #fbf1c7
url_color             #af3a03

# Normal colors
color0  #fbf1c7
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #7c6f64

# Bright colors
color8  #928374
color9  #9d0006
color10 #79740e
color11 #b57614
color12 #076678
color13 #8f3f71
color14 #427b58
color15 #3c3836

# Tab bar
tab_bar_margin_color    #fbf1c7
tab_bar_background      #fbf1c7
active_tab_foreground   #fbf1c7
active_tab_background   #d79921
active_tab_font_style   bold
inactive_tab_foreground #7c6f64
inactive_tab_background #ebdbb2
inactive_tab_font_style normal
