####################
### APPLICATIONS ###
####################
bind = SUPER,       RETURN, exec, $terminal
bind = SUPER SHIFT, RETURN, exec, $browser
bind = SUPER SHIFT, B,      exec, $browser
bind = SUPER SHIFT, F,      exec, $fileManager
bind = SUPER,       SPACE,  exec, $menu
