###################
### UTILITIES #####
###################

# Toggle top bar (waybar)
bind = SUPER SHIFT, SPACE, exec, pkill -SIGUSR1 waybar

# Notifications (mako)
bind = SUPER,       COMMA, exec, makoctl dismiss
bind = SUPER SHIFT, COMMA, exec, makoctl dismiss --all
bind = SUPER ALT,   COMMA, exec, makoctl restore

# Toggle nightlight (hyprsunset)
bind = SUPER CTRL, N, exec, pkill hyprsunset || hyprsunset -t 4000

# Toggle locking on idle (hypridle)
bind = SUPER CTRL, I, exec, pkill hypridle || hypridle

# Screenshots (grim + slurp + satty, stile omarchy)
bind = ,          PRINT, exec, ~/.config/hypr/scripts/screenshot.sh output
bind = SUPER,     PRINT, exec, ~/.config/hypr/scripts/screenshot.sh region
bind = SUPER ALT, PRINT, exec, ~/.config/hypr/scripts/screenshot.sh window

# Color picker (hyprpicker)
bind = SUPER CTRL, PRINT, exec, pkill hyprpicker || hyprpicker -a

# Zoom (requires jq)
bind = SUPER CTRL,     Z, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bind = SUPER CTRL ALT, Z, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bind = SUPER CTRL, L, exec, hyprlock
