####################
### WINDOW RULES ###
####################
# See https://wiki.hypr.land/Configuring/Basics/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.*

# Fix XWayland unmanaged floating windows stealing focus
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# Omarchy-style global window transparency.
# Rimuovi questa riga se preferisci finestre completamente opache.
windowrulev2 = opacity 0.97 0.9, class:.*
